AWSTemplateFormatVersion: 2010-09-09
Description: This template deploy CloudFront and S3.
# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------#
Parameters:
  BucketName:
    Type: String
    Description: A name for the bucket.
# ------------------------------------------------------------#
# Resources
# ------------------------------------------------------------#
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: "Allow"
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${BucketName}/*
  CloudFront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - S3Bucket
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        Origins:
          - Id: !Ref S3Bucket
            DomainName: !GetAtt S3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: !Ref S3Bucket
          Compress: true
          ViewerProtocolPolicy: allow-all
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Name: CachingOptimized
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 1
