version: "3.7"
services:
  prisma-db:
    container_name: migrataion-training
    image: postgres:12
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: migration-training
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"